In [4]:
import numpy as np

# Slicing

In [10]:
q = np.arange(10)
print(q)
print(q[5:])
print(q[::5])
print(q[::-1])

[0 1 2 3 4 5 6 7 8 9]
[5 6 7 8 9]
[0 5]
[9 8 7 6 5 4 3 2 1 0]


# Cumsum

In the event of using future rewards. Sequentially start summing closer and closer to the end

In [13]:
a = np.arange(10)
b = a[::-1].cumsum(axis=0)[::-1]
print(a)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[45 45 44 42 39 35 30 24 17  9]


In [35]:
discount = 0.995
rewards = list(range(10))

discount = discount**np.arange(len(rewards))
discounted_rewards = np.asarray(rewards)*discount[:,np.newaxis]
print(discount)
print(discounted_rewards.shape)
print(discounted_rewards)

[1.         0.995      0.990025   0.98507488 0.9801495  0.97524875
 0.97037251 0.96552065 0.96069304 0.95588958]
(10, 10)
[[0.         1.         2.         3.         4.         5.
  6.         7.         8.         9.        ]
 [0.         0.995      1.99       2.985      3.98       4.975
  5.97       6.965      7.96       8.955     ]
 [0.         0.990025   1.98005    2.970075   3.9601     4.950125
  5.94015    6.930175   7.9202     8.910225  ]
 [0.         0.98507488 1.97014975 2.95522463 3.9402995  4.92537438
  5.91044925 6.89552412 7.880599   8.86567388]
 [0.         0.9801495  1.960299   2.9404485  3.920598   4.9007475
  5.880897   6.8610465  7.841196   8.82134551]
 [0.         0.97524875 1.95049751 2.92574626 3.90099501 4.87624377
  5.85149252 6.82674127 7.80199002 8.77723878]
 [0.         0.97037251 1.94074502 2.91111753 3.88149004 4.85186255
  5.82223506 6.79260757 7.76298007 8.73335258]
 [0.         0.96552065 1.93104129 2.89656194 3.86208259 4.82760323
  5.79312388 6.758644

In [37]:
# convert rewards to future rewards
future_rewards = discounted_rewards[::-1].cumsum(axis=0)[::-1]

mean = np.mean(rewards_future, axis=1)
std = np.std(rewards_future, axis=1) + 1.0e-10

rewards_normalized = (future_rewards - mean[:,np.newaxis])/std[:,np.newaxis]

In [38]:
print(future_rewards)
print(rewards_normalized)

[[ 0.          9.77797391 19.55594781 29.33392172 39.11189563 48.88986953
  58.66784344 68.44581735 78.22379125 88.00176516]
 [ 0.          8.77797391 17.55594781 26.33392172 35.11189563 43.88986953
  52.66784344 61.44581735 70.22379125 79.00176516]
 [ 0.          7.78297391 15.56594781 23.34892172 31.13189563 38.91486953
  46.69784344 54.48081735 62.26379125 70.04676516]
 [ 0.          6.79294891 13.58589781 20.37884672 27.17179563 33.96474453
  40.75769344 47.55064235 54.34359125 61.13654016]
 [ 0.          5.80787403 11.61574806 17.4236221  23.23149613 29.03937016
  34.84724419 40.65511822 46.46299225 52.27086629]
 [ 0.          4.82772453  9.65544906 14.48317359 19.31089812 24.13862266
  28.96634719 33.79407172 38.62179625 43.44952078]
 [ 0.          3.85247578  7.70495156 11.55742733 15.40990311 19.26237889
  23.11485467 26.96733045 30.81980622 34.672282  ]
 [ 0.          2.88210327  5.76420654  8.64630981 11.52841307 14.41051634
  17.29261961 20.17472288 23.05682615 25.93892942]


In [27]:
mean = np.mean(future_rewards,axis=1)
std = np.std(future_rewards,axis=1) + 1e-10
rewards_normalized = (future_rewards - mean[:,np.newaxis])/std[:,np.newaxis]

In [32]:
print(mean.shape)
print(std.shape)
print(rewards_normalized.shape)
print(rewards_normalized)

(10,)
(10,)
(10, 10)
[[-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
   0.52223297  0.87038828  1.21854359  1.5666989 ]
 [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
   0.52223297  0.87038828  1.21854359  1.5666989 ]
 [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
   0.52223297  0.87038828  1.21854359  1.5666989 ]
 [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
   0.52223297  0.87038828  1.21854359  1.5666989 ]
 [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
   0.52223297  0.87038828  1.21854359  1.5666989 ]
 [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
   0.52223297  0.87038828  1.21854359  1.5666989 ]
 [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
   0.52223297  0.87038828  1.21854359  1.5666989 ]
 [-1.5666989  -1.21854359 -0.87038828 -0.52223297 -0.17407766  0.17407766
   0.52223297  0.87038828  1.2

# Newaxis

Creates a new axis to fill out.
*For future rewards*

In [15]:
rewards = list(range(10))
discount = np.full(10,0.995)
print(discount)
print(rewards)
discounted_rewards = np.asarray(rewards)*discount[:,np.newaxis]
print(discounted_rewards)

[0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995 0.995]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[[0.    0.995 1.99  2.985 3.98  4.975 5.97  6.965 7.96  8.955]
 [0.    0.995 1.99  2.985 3.98  4.975 5.97  6.965 7.96  8.955]
 [0.    0.995 1.99  2.985 3.98  4.975 5.97  6.965 7.96  8.955]
 [0.    0.995 1.99  2.985 3.98  4.975 5.97  6.965 7.96  8.955]
 [0.    0.995 1.99  2.985 3.98  4.975 5.97  6.965 7.96  8.955]
 [0.    0.995 1.99  2.985 3.98  4.975 5.97  6.965 7.96  8.955]
 [0.    0.995 1.99  2.985 3.98  4.975 5.97  6.965 7.96  8.955]
 [0.    0.995 1.99  2.985 3.98  4.975 5.97  6.965 7.96  8.955]
 [0.    0.995 1.99  2.985 3.98  4.975 5.97  6.965 7.96  8.955]
 [0.    0.995 1.99  2.985 3.98  4.975 5.97  6.965 7.96  8.955]]


In [ ]:
# 