In [1]:
import math
import operator
import numpy as np
import random
from collections import namedtuple, deque
import matplotlib.pyplot as plt
import imageio
import copy

from multiprocessing import Process, Pipe

is_ipython = 'inline' in plt.get_backend()
if is_ipython:
    from IPython import display

plt.ion()

import gym

# Overview

- We have a specific Agent (DDPG) instance.
- We copy the agent K times
- We copy the Env K times
- We run all actors in parallel in the seperate envs
- We combine the observations into one for each agent
- Each agent is updated by its own critic
- Each policy only acts according to its local environment


# Multi Agent with Env processing

First lets create this by iterating sequentially. Then we can later try async if we have time

In [ ]:
class MultiAgent(object):
    def __init__(self,policy,env)

In [4]:
a = np.arange(20)

In [6]:
c = a[::4]
b = a[1::4]
d = a[2::4]

print(a[::4])
print(a[1::4])
print(a[2::4])

[ 0  4  8 12 16]
[ 1  5  9 13 17]
[ 2  6 10 14 18]


In [10]:
t,r,e = map(lambda x: x[0], [c,b,d])

In [11]:
print(t,r,e)

0 1 2


In [12]:
for i,d in enumerate(c):
    print(i,d)

0 0
1 4
2 8
3 12
4 16
